[package]
name = "example-objc2-network-browser"
version = "0.1.0"
edition = "2021"

[dependencies]
block2 = "0.5.1"
dispatch = "0.2.0"
int-enum = "1.1.2"
objc2 = "0.5.2"
strum = { version = "0.26.3", features = ["derive"] }
tokio = { version = "1.41.0", features = ["full"] }
